/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as chroniclePriceProviderSol from "./ChroniclePriceProvider.sol";
export type { chroniclePriceProviderSol };
export type { ChainlinkPriceProvider } from "./ChainlinkPriceProvider";
export type { ManualPriceProvider } from "./ManualPriceProvider";
export type { NativeTokenPayment } from "./NativeTokenPayment";
