/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChronicle,
  IChronicleInterface,
} from "../../../../contracts/core/ChroniclePriceProvider.sol/IChronicle";

const _abi = [
  {
    inputs: [],
    name: "read",
    outputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "readWithAge",
    outputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "age",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IChronicle__factory {
  static readonly abi = _abi;
  static createInterface(): IChronicleInterface {
    return new utils.Interface(_abi) as IChronicleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChronicle {
    return new Contract(address, _abi, signerOrProvider) as IChronicle;
  }
}
