/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISelfKisser,
  ISelfKisserInterface,
} from "../../../../contracts/core/ChroniclePriceProvider.sol/ISelfKisser";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "oracle",
        type: "address",
      },
    ],
    name: "selfKiss",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISelfKisser__factory {
  static readonly abi = _abi;
  static createInterface(): ISelfKisserInterface {
    return new utils.Interface(_abi) as ISelfKisserInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISelfKisser {
    return new Contract(address, _abi, signerOrProvider) as ISelfKisser;
  }
}
