/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPriceProvider,
  IPriceProviderInterface,
} from "../../../../contracts/core/NativeTokenPayment.sol/IPriceProvider";

const _abi = [
  {
    inputs: [],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPriceProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IPriceProviderInterface {
    return new utils.Interface(_abi) as IPriceProviderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPriceProvider {
    return new Contract(address, _abi, signerOrProvider) as IPriceProvider;
  }
}
