/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface IChronicleInterface extends utils.Interface {
  functions: {
    "read()": FunctionFragment;
    "readWithAge()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "read" | "readWithAge"): FunctionFragment;

  encodeFunctionData(functionFragment: "read", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "readWithAge",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "read", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "readWithAge",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IChronicle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IChronicleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    read(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    readWithAge(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { value: BigNumber; age: BigNumber }>;
  };

  read(overrides?: CallOverrides): Promise<BigNumber>;

  readWithAge(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { value: BigNumber; age: BigNumber }>;

  callStatic: {
    read(overrides?: CallOverrides): Promise<BigNumber>;

    readWithAge(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { value: BigNumber; age: BigNumber }>;
  };

  filters: {};

  estimateGas: {
    read(overrides?: CallOverrides): Promise<BigNumber>;

    readWithAge(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    read(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    readWithAge(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
